/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Grand_Canyon_Glass.glb -o src/components/GrandCanyonGlass.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Grand_Canyon_Glass.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Glass_Main.geometry} material={materials.Glass} />
      <mesh geometry={nodes.Glass_Base.geometry} material={materials.Glass_Base} />
    </group>
  )
}

useGLTF.preload('/Grand_Canyon_Glass.glb')
